pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/byoungjuchae/pytorch-to-onnx.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'cd fastapi_onnx_docker_classification/app/'
                docker.build("fast")
                }
            }
        
        stage('Push Docker Image') {
            steps {
                sh 'docker run -d fast'
                }
            }
    }
}

        
