pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/byoungjuchae/pytorch-to-onnx.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                cd 'fastapi_onnx_docker_classification'
                cd 'app'
                sh 'docker build -t fast .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker run -d fast'
                }
            }
        }

        

    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
