
pipeline {
    agent any
    environment{
    CONTENT ='fast'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/byoungjuchae/pytorch-to-onnx.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('/fastapi_onnx_docker_jenkins/app'){

                    script{
                        sh 'docker build -t ${CONTENT}:0.1v  -f dockerfile .'
              
                        }
                }
            }
        
        // stage('Push Docker Image') {
        //     steps {
        //         script{
        //             sh 'docker run -d fast'
                
        //         }
        //     }
    }
    }
}