
pipeline {
    agent any
    environment{
    CONTENT ='fast' 
    REPOSITORY = "wpdhkd1642/fast"
    }
 
    stages {
        stage('Checkout') {
            steps{
                git 'https://github.com/byoungjuchae/pytorch-to-onnx.git'
            }
        }
        stage('Build Docker Image') {
            steps{
                dir('fastapi_onnx_docker_jenkins/app/'){
                   sh 'docker build . -t fast '
                }
            }
        }
        stage('Push'){
            steps{
                script{
                    sh 'docker login'
                    sh 'docker push $REPOSITORY:0.1v'
                }
            }
        }
    }
}