
pipeline {
    agent any
    environment{
    CONTENT ='fast'
    }
    tools{
        docker 'docker'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/byoungjuchae/pytorch-to-onnx.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('fastapi_onnx_docker_jenkins/app/'){
                   sh 'docker build -t fast -f Dockerfile .'
                }
            }
        
        }
    }
}